### ISSUE TITLE
Fehler beim Testen mit der BW-Bank

### ISSUE THREAD

**Issue by Selichio** [jschyma/open_fints_js_client#20]
Hi,

habe gerade versucht, eine Connection zur BW-Bank herzustellen. Ich habe hierfür den Beispielcode verwendet und auf die BW-Bank Spezifikation angepasst und um den Logger erweitert:

var bankenliste = {
                '60050101':{'blz':60050101,'url':"https://hbci.bw-bank.de"}
};
var client = new FinTSClient('60050101',"9999999","12345",bankenliste, log);

 Folgendes Resultat habe ich erhalten: 

{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"connection_establish","level":20,"step":1,"msg":"Start First Connection","time":"2016-04-04T15:56:06.027Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"gv","level":20,"gv":"HKVVB","msg":"Send HKVVB,HKIDN","time":"2016-04-04T15:56:06.033Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"connection","level":10,"raw_data":"HNHBK:1:3+000000000359+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20160404:175606+2:2:13:@8@\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000:5:1+280:60050101:9999999:V:0:0+0'HNVSD:999:1+@199@HNSHK:2:4+PIN:1+999+1+1+1+1::0+1+1:20160404:175606+1:999:1+6:10:16+280:60050101:9999999:S:0:0'HKIDN:3:2+280:60050101+9999999+0+1'HKVVB:4:3+0+0+0+Open-FinTS-JS-Client+4'HKSYN:5:3+0'HNSHA:6:2+1++12345''HNHBS:7:1+1'","send_or_recv":"send","msg":"Connection Data Trace","time":"2016-04-04T15:56:06.034Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"connection","level":20,"host":"hbci.bw-bank.de","port":null,"path":"/","msg":"Connect to Host","time":"2016-04-04T15:56:06.036Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"connection","level":20,"host":"hbci.bw-bank.de","port":null,"path":"/","msg":"Request finished","time":"2016-04-04T15:56:06.354Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"connection","level":10,"raw_data":"","send_or_recv":"recv","msg":"Connection Data Trace","time":"2016-04-04T15:56:06.366Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"gv","level":50,"gv":"HKVVB","msg":"Error while analyse HKVVB Response Wrong HIRMG response code","time":"2016-04-04T15:56:06.368Z","v":0}
{"name":"demo_fints_logger","hostname":"Denniss-iMac.fritz.box","pid":4796,"area":"gv","level":50,"err":{"message":"Cannot read property 'getEl' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'getEl' of undefined\n    at /private/var/tmp/TEST/node_modules/open-fin-ts-js-client/lib/FinTSClient.js:597:73\n    at int_callback (/private/var/tmp/TEST/node_modules/open-fin-ts-js-client/lib/FinTSClient.js:1050:4)\n    at IncomingMessage.<anonymous> (/private/var/tmp/TEST/node_modules/open-fin-ts-js-client/lib/FinTSClient.js:1082:5)\n    at emitNone (events.js:85:20)\n    at IncomingMessage.emit (events.js:179:7)\n    at endReadableNT (_stream_readable.js:906:12)\n    at nextTickCallbackWith2Args (node.js:475:9)\n    at process._tickCallback (node.js:389:17)"},"msg":"{ gv: 'HKVVB' } 'Unhandled callback Error in HKVVB,HKIDN'","time":"2016-04-04T15:56:06.370Z","v":0}

**Comment by jschyma** [comment]
Hi,

ich muss leider gleich sagen, ich habe zurzeit nur wenig Zeit mir den Fehler genauer anzuschauen.
Jedoch:

1. Sie haben zwar die BLZ und die URL angepasst aber nicht Ihren Benutzer und Ihre PIN eingegeben.

var client = new FinTSClient('60050101',"9999999","12345",bankenliste, log);
Stattdessen stehen hier 9999 und 12345.

Haben Sie das hier nur so gepostet und der Fehler tritt auch auf, wenn Sie Ihre richtigen Daten eingeben?
Achtung: Sollten Sie nochmal etwas Posten - vorallem auch Logs - immer darauf achten, dass weder Ihre PIN noch Ihre Kontonummer oder andere sensible Daten im Log enthalten sind.
Da Sie die Logs mit den Dummy Daten gepostet haben, ist das jetzt hier kein Problem.

2. Die ersten Fehler hängen mit Ihrer Bunyan Konfiguration zusammen.
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

3. Trotz falsch eingegebener Daten sollte natürlich das Programm nicht abbrechen.
Ich schaue mir den Fehler demnächst an. Ich bitte Sie aber noch um etwa 1-2Monate gedult, da ich vorher keine Zeit haben werde.

Sollten Sie zwischenzeitlich selbst auf eine Lösung kommen, bitte ich Sie Ihren Lösungswegen entweder direkt als PullRequest oder durch Beschreibung in diesem Issue dem Projekt beizutragen.

Viele Grüße
Jens Schyma
